agent:
  max_tokens: 2048
  model: deepseek-coder:6.7b
  temperature: 0.2
embeddings:
  device: cpu
  model: sentence-transformers/all-MiniLM-L6-v2
indexing:
  chunk_overlap: 200
  chunk_size: 1200
  max_files: 10000
languages:
  csharp:
    conventions:
    - stylecop
    - editorconfig
    excluded_dirs:
    - bin
    - obj
    - packages
    extensions:
    - .cs
    frameworks:
    - dotnet
    - aspnet
    - blazor
    patterns:
    - mvc
    - repository
    - factory
    - dependency_injection
    separators:
    - '

      public class '
    - '

      public '
    - '

      private '
    - '


      '
    - '

      '
    - ' '
    test_frameworks:
    - xunit
    - nunit
    - mstest
  go:
    conventions:
    - gofmt
    - golint
    - golangci-lint
    excluded_dirs:
    - vendor
    extensions:
    - .go
    frameworks:
    - gin
    - echo
    - fiber
    patterns:
    - repository
    - factory
    - adapter
    separators:
    - '

      func '
    - '

      type '
    - '


      '
    - '

      '
    - ' '
    test_frameworks:
    - testing
    - ginkgo
    - testify
  java:
    conventions:
    - checkstyle
    - spotbugs
    - pmd
    excluded_dirs:
    - target
    - build
    - .gradle
    extensions:
    - .java
    frameworks:
    - spring
    - springboot
    - maven
    - gradle
    patterns:
    - mvc
    - repository
    - factory
    - adapter
    - dependency_injection
    separators:
    - '

      public class '
    - '

      public '
    - '

      private '
    - '


      '
    - '

      '
    - ' '
    test_frameworks:
    - junit
    - testng
    - mockito
  javascript:
    conventions:
    - eslint
    - prettier
    - standard
    excluded_dirs:
    - node_modules
    - dist
    - build
    - .next
    - .nuxt
    extensions:
    - .js
    - .jsx
    - .mjs
    frameworks:
    - react
    - vue
    - angular
    - express
    - nestjs
    - nextjs
    patterns:
    - mvc
    - component
    - observer
    - module
    separators:
    - '

      class '
    - '

      function '
    - '

      const '
    - '


      '
    - '

      '
    - ' '
    test_frameworks:
    - jest
    - mocha
    - vitest
    - cypress
  python:
    conventions:
    - pep8
    - black
    - flake8
    - pylint
    excluded_dirs:
    - venv
    - env
    - .venv
    - site-packages
    - .tox
    extensions:
    - .py
    - .pyw
    - .pyx
    frameworks:
    - django
    - flask
    - fastapi
    - tornado
    - pyramid
    patterns:
    - mvc
    - repository
    - factory
    - singleton
    separators:
    - '

      class '
    - '

      def '
    - '


      '
    - '

      '
    - ' '
    test_frameworks:
    - pytest
    - unittest
    - nose2
  rust:
    conventions:
    - rustfmt
    - clippy
    excluded_dirs:
    - target
    extensions:
    - .rs
    frameworks:
    - actix
    - rocket
    - warp
    patterns:
    - repository
    - factory
    - builder
    separators:
    - '

      fn '
    - '

      struct '
    - '

      impl '
    - '


      '
    - '

      '
    - ' '
    test_frameworks:
    - cargo test
    - rstest
  typescript:
    conventions:
    - eslint
    - prettier
    - tslint
    excluded_dirs:
    - node_modules
    - dist
    - build
    extensions:
    - .ts
    - .tsx
    frameworks:
    - angular
    - nestjs
    - nextjs
    - express
    patterns:
    - mvc
    - component
    - decorator
    - observer
    separators:
    - '

      class '
    - '

      function '
    - '

      interface '
    - '


      '
    - '

      '
    - ' '
    test_frameworks:
    - jest
    - mocha
    - vitest
